db:
    db_url: ENC[AES256_GCM,data:CS37zjUSv3cz1g==,iv:86MNum5JYRJVacSGJVZy+6YbtY0Do4NOLMsNe1x32bM=,tag:PK8FP924jiFB+jh8DwX2iw==,type:str]
    db_port: ENC[AES256_GCM,data:x/N9JA==,iv:x13NluFZlZb24kD2WLM/EwbBKHWjU9FkzBDb4YJevFY=,tag:kKcBKx8yrb7vAnTa7xMeWw==,type:int]
    db_pass: ENC[AES256_GCM,data:ClAjjw==,iv:QAFbXxbgp+Mr1n48QV5udVKbJ/017LF8EcLVJRos4fk=,tag:z+5SoiErszYOIrqxnVhiqA==,type:str]
api:
    api_url: ENC[AES256_GCM,data:GEvDsuV1Sy8/4udr8H8g+FwB6w==,iv:SL1A9gN3JpuoyqvoVUTOKJVk/hcViwPevAurxhB+rVY=,tag:UngsKrE0UiET8RDyhPPA1w==,type:str]
    token: ENC[AES256_GCM,data:MSdLcvnMnRPs,iv:Wl+dhLZps86sZhudtd5YadwNMxlExwPt/wNmPqbYyHo=,tag:TW6W/+NrAfNqNBY/DVO6lw==,type:int]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-1:899632766336:key/3b816368-7a67-47ba-912c-b6f8802a06d6
        created_at: '2020-10-07T21:13:24Z'
        enc: AQICAHiWDTwxGiwY4KEdtfCPTHcxmOjU+YqpeOXuFCggL35iXAG6r4NeAXr7uA9LMcnKMlZKAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5UqX2HurJhGBLrbUAgEQgDtOjNz0ryJzmT1mYgory2bHfnYsmYYD9D2XAWh1Y3Im+J1nAAWnp/geY4zwPbyPtVfrDdM9mTK65DPK/g==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-10-07T21:13:52Z'
    mac: ENC[AES256_GCM,data:U+xGs7v0rqAAj8Y2Aidp/j110IN9rTiv3ApoFJduVrYglC+la/hNz91ErrUZFty5zo8/hcnlkX4lmD4r0LBZgpfEAxh3UJXScUX9oPA1COf0FKHTRbtnbbPcje0u+MPSfSV8BowoQUR3myLAEeUPp/oIsXseXPZtNcoJjYZP/l4=,iv:FIITQY7jJ3EvA8klGZoaGmARYA3L1gYJTMG6aAVBCqo=,tag:MPcnralD+dskr+p/Sztpjw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.5.0
