db:
    db_url: ENC[AES256_GCM,data:KWMY08/87Q==,iv:9e1OZI9YlqXvAL2oldEeeLjTLFGYwS1YxjQAZgEM6tg=,tag:Vct1+qIyZluN6pFStnE3kw==,type:str]
    db_port: ENC[AES256_GCM,data:TAx91Q==,iv:+IabONC5VCcmGmPnSlAF/VR+hSyf8pZkcOooGg2zY1A=,tag:5WRqxr3eEFrsIIm6qbr7vw==,type:int]
    db_pass: ENC[AES256_GCM,data:rnnO5BndBhrFeJs=,iv:t/uVxBWlYoxssjcn5VCuWpwf5NuTtE1bcXkTlH+RqIE=,tag:+w941B1XD4sSGzEf5vQJGw==,type:str]
api:
    api_url: ENC[AES256_GCM,data:XBcXtlBIbg6NBfEnf7EGQzimDZaEXw==,iv:18S8HTVsuAUhR9vYNgJdbKUz1hT2EvTE+3bl5YqKX1I=,tag:/GyKH/7WiAGJ/n8eADyxzw==,type:str]
    token: ENC[AES256_GCM,data:8lu/6uKij7ExrvA=,iv:CilsMZSoweC8cS9vnQX3uKDGWkf84bR+seT3SZqaw58=,tag:NNOQ5tAgq1RT7A3HRzVusA==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-1:899632766336:key/3b816368-7a67-47ba-912c-b6f8802a06d6
        created_at: '2020-10-07T21:14:36Z'
        enc: AQICAHiWDTwxGiwY4KEdtfCPTHcxmOjU+YqpeOXuFCggL35iXAFSy4Tpabx0Esrmy2ZpngJ0AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMnK4XEK1fyRdGdBVrAgEQgDtA1I49NbbBMllrEWmcGbSWETxMJQdwj7TlHdnGFlvroZMa0R2tGWHERT51TZogvib9hM4ralIg1lecsg==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-10-16T19:31:13Z'
    mac: ENC[AES256_GCM,data:NQz2sRF/0yxJjXnbi4/AZhaK5GfHqd2zVpEiH3ZrdrBwdREgOlpiIzv7FeVObNKjhZc5frh7xBfNbFGtD15mEv0B5f5zrT4/4pJlm/EGb97GGIXmuJ2TmjAy5NK8nCSOt/gP5eZhkwNia8AnJfWzOPdPH8KYjFDQ4dfCnHNLEAg=,iv:aMm6Yhmlki+OfTE86Cu8X4ehZhK+4J9FHrsUkCPyYbs=,tag:+FY6mx+8hTksnci308Hd5Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.5.0
