db:
    db_url: ENC[AES256_GCM,data:KWMY08/87Q==,iv:9e1OZI9YlqXvAL2oldEeeLjTLFGYwS1YxjQAZgEM6tg=,tag:Vct1+qIyZluN6pFStnE3kw==,type:str]
    db_port: ENC[AES256_GCM,data:455cUg==,iv:wzRsNSXVP40R/+0u5p2xJx6v1heVLjI/vUA8UPDTUIQ=,tag:Ed09D/6x5IGwZ49taO04Rw==,type:int]
    db_pass: ENC[AES256_GCM,data:rnnO5BndBhrFeJs=,iv:t/uVxBWlYoxssjcn5VCuWpwf5NuTtE1bcXkTlH+RqIE=,tag:+w941B1XD4sSGzEf5vQJGw==,type:str]
api:
    api_url: ENC[AES256_GCM,data:XBcXtlBIbg6NBfEnf7EGQzimDZaEXw==,iv:18S8HTVsuAUhR9vYNgJdbKUz1hT2EvTE+3bl5YqKX1I=,tag:/GyKH/7WiAGJ/n8eADyxzw==,type:str]
    token: ENC[AES256_GCM,data:8lu/6uKij7ExrvA=,iv:CilsMZSoweC8cS9vnQX3uKDGWkf84bR+seT3SZqaw58=,tag:NNOQ5tAgq1RT7A3HRzVusA==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-1:899632766336:key/3b816368-7a67-47ba-912c-b6f8802a06d6
        created_at: '2020-10-07T21:14:36Z'
        enc: AQICAHiWDTwxGiwY4KEdtfCPTHcxmOjU+YqpeOXuFCggL35iXAFSy4Tpabx0Esrmy2ZpngJ0AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMnK4XEK1fyRdGdBVrAgEQgDtA1I49NbbBMllrEWmcGbSWETxMJQdwj7TlHdnGFlvroZMa0R2tGWHERT51TZogvib9hM4ralIg1lecsg==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-10-07T21:14:36Z'
    mac: ENC[AES256_GCM,data:NiVn6qAobJgfI3f33cKR9/aIC2L8j/ZGyGKBFatsLIv8F2rR7VUm1TIgOxgxaz8ulp97E1bNJLB3FxBQrMdCwUGoLgrQYxF1AudRSToO//DtQfgkxD0gZVkSul2KQxZupsLxGjMjqlQ3gA0+TLLF4+lB6cvlXktyGRH23FuQn4M=,iv:XyQas8PBofGLA9je5itCgvywR6YZrjP+VTJb62fBsj0=,tag:zVi90eWzGLMavwzNTB3BSA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.5.0
